In [3]:
import pandas as pd
from datetime import datetime

In [4]:
data = pd.read_csv('airpod_reviews.csv')

In [5]:
data.head()

,username_name,username_rating,username_inital_statement,username_country,username_verified,username_review,username_usefulness
0,Asia underwood,4.0 out of 5 stars,It has good noise cancellation the only proble...,Reviewed in the United States ðŸ‡ºðŸ‡¸ on February 1...,Verified Purchase,"so when I bought these , I knew what i wanted ...",7 people found this helpful
1,Katie,4.0 out of 5 stars,Love these Headphones,Reviewed in the United States ðŸ‡ºðŸ‡¸ on February 2...,Verified Purchase,I bought these headphones last year and they h...,6 people found this helpful
2,Sean Connolly,4.0 out of 5 stars,Solid,Reviewed in the United States ðŸ‡ºðŸ‡¸ on December 1...,Verified Purchase,"The noise cancellation feature is very cool, a...",6 people found this helpful
3,Michelle,5.0 out of 5 stars,BUY IT RN,Reviewed in the United States ðŸ‡ºðŸ‡¸ on January 17...,Verified Purchase,i was a little bit skeptical at first because ...,7 people found this helpful
4,Jayden,5.0 out of 5 stars,Greta product slightly dirty,Reviewed in the United States ðŸ‡ºðŸ‡¸ on February 1...,Verified Purchase,Everything works! The only down sid Eid there ...,NaN

In [6]:
data.count()

username_name                1996
username_rating              1996
username_inital_statement    1996
username_country             1996
username_verified            1941
username_review              1979
username_usefulness           424
dtype: int64

In [7]:
data.shape[0]

1996

In [8]:
data = data.rename(columns={
    'username_name':'username',
    'username_rating':'rating',
    'username_inital_statement':'initial_statement',
    'username_verified':'verified',
    'username_review':'review',
    'username_usefulness':'usefulness',
})

In [9]:
data.head()

,username,rating,initial_statement,username_country,verified,review,usefulness
0,Asia underwood,4.0 out of 5 stars,It has good noise cancellation the only proble...,Reviewed in the United States ðŸ‡ºðŸ‡¸ on February 1...,Verified Purchase,"so when I bought these , I knew what i wanted ...",7 people found this helpful
1,Katie,4.0 out of 5 stars,Love these Headphones,Reviewed in the United States ðŸ‡ºðŸ‡¸ on February 2...,Verified Purchase,I bought these headphones last year and they h...,6 people found this helpful
2,Sean Connolly,4.0 out of 5 stars,Solid,Reviewed in the United States ðŸ‡ºðŸ‡¸ on December 1...,Verified Purchase,"The noise cancellation feature is very cool, a...",6 people found this helpful
3,Michelle,5.0 out of 5 stars,BUY IT RN,Reviewed in the United States ðŸ‡ºðŸ‡¸ on January 17...,Verified Purchase,i was a little bit skeptical at first because ...,7 people found this helpful
4,Jayden,5.0 out of 5 stars,Greta product slightly dirty,Reviewed in the United States ðŸ‡ºðŸ‡¸ on February 1...,Verified Purchase,Everything works! The only down sid Eid there ...,NaN

In [10]:
data['rating'] = data['rating'].str[0]

In [11]:
data.head()

,username,rating,initial_statement,username_country,verified,review,usefulness
0,Asia underwood,4,It has good noise cancellation the only proble...,Reviewed in the United States ðŸ‡ºðŸ‡¸ on February 1...,Verified Purchase,"so when I bought these , I knew what i wanted ...",7 people found this helpful
1,Katie,4,Love these Headphones,Reviewed in the United States ðŸ‡ºðŸ‡¸ on February 2...,Verified Purchase,I bought these headphones last year and they h...,6 people found this helpful
2,Sean Connolly,4,Solid,Reviewed in the United States ðŸ‡ºðŸ‡¸ on December 1...,Verified Purchase,"The noise cancellation feature is very cool, a...",6 people found this helpful
3,Michelle,5,BUY IT RN,Reviewed in the United States ðŸ‡ºðŸ‡¸ on January 17...,Verified Purchase,i was a little bit skeptical at first because ...,7 people found this helpful
4,Jayden,5,Greta product slightly dirty,Reviewed in the United States ðŸ‡ºðŸ‡¸ on February 1...,Verified Purchase,Everything works! The only down sid Eid there ...,NaN

In [12]:
data.head()

,username,rating,initial_statement,username_country,verified,review,usefulness
0,Asia underwood,4,It has good noise cancellation the only proble...,Reviewed in the United States ðŸ‡ºðŸ‡¸ on February 1...,Verified Purchase,"so when I bought these , I knew what i wanted ...",7 people found this helpful
1,Katie,4,Love these Headphones,Reviewed in the United States ðŸ‡ºðŸ‡¸ on February 2...,Verified Purchase,I bought these headphones last year and they h...,6 people found this helpful
2,Sean Connolly,4,Solid,Reviewed in the United States ðŸ‡ºðŸ‡¸ on December 1...,Verified Purchase,"The noise cancellation feature is very cool, a...",6 people found this helpful
3,Michelle,5,BUY IT RN,Reviewed in the United States ðŸ‡ºðŸ‡¸ on January 17...,Verified Purchase,i was a little bit skeptical at first because ...,7 people found this helpful
4,Jayden,5,Greta product slightly dirty,Reviewed in the United States ðŸ‡ºðŸ‡¸ on February 1...,Verified Purchase,Everything works! The only down sid Eid there ...,NaN

In [13]:
type(data['rating'])

pandas.core.series.Series

In [14]:
data['rating'] = data['rating'].astype(int)

In [15]:
data['verified'] = data['verified'].replace({'Verified Purchase':1, '':0})

In [16]:
data.head()

,username,rating,initial_statement,username_country,verified,review,usefulness
0,Asia underwood,4,It has good noise cancellation the only proble...,Reviewed in the United States ðŸ‡ºðŸ‡¸ on February 1...,1,"so when I bought these , I knew what i wanted ...",7 people found this helpful
1,Katie,4,Love these Headphones,Reviewed in the United States ðŸ‡ºðŸ‡¸ on February 2...,1,I bought these headphones last year and they h...,6 people found this helpful
2,Sean Connolly,4,Solid,Reviewed in the United States ðŸ‡ºðŸ‡¸ on December 1...,1,"The noise cancellation feature is very cool, a...",6 people found this helpful
3,Michelle,5,BUY IT RN,Reviewed in the United States ðŸ‡ºðŸ‡¸ on January 17...,1,i was a little bit skeptical at first because ...,7 people found this helpful
4,Jayden,5,Greta product slightly dirty,Reviewed in the United States ðŸ‡ºðŸ‡¸ on February 1...,1,Everything works! The only down sid Eid there ...,NaN

In [17]:
data.tail()

,username,rating,initial_statement,username_country,verified,review,usefulness
1991,PEDRO VALDOVINOS GAONA,2,Que el producto estÃ© en buenas condiciones.,"Reviewed in Mexico ðŸ‡²ðŸ‡½ on June 24, 2021",1,El producto se descargaba muy rÃ¡pido incluso l...,NaN
1992,maac08,5,muy recomendables,"Reviewed in Mexico ðŸ‡²ðŸ‡½ on June 1, 2021",1,excelentes para usar en llamadas,NaN
1993,Maximiliano,1,"La caja de los audÃ­fonos me llegÃ³ , de que est...","Reviewed in Mexico ðŸ‡²ðŸ‡½ on September 19, 2022",1,Al parecer en algÃºn lugar se mojo la caja de l...,One person found this helpful
1994,Antonio MerÃ©,5,Excelente,"Reviewed in Mexico ðŸ‡²ðŸ‡½ on May 22, 2021",1,Excelente,NaN
1995,diego,1,Audifono derecho COMPLETAMENTE inservible.,"Reviewed in Mexico ðŸ‡²ðŸ‡½ on October 4, 2021",1,Todo el empaquetado estaba en muy buenas condi...,One person found this helpful

In [18]:
data['verified'].isnull().sum()

55

In [19]:
data['verified'] = data['verified'].fillna(0)

In [20]:
data['verified'].isnull().sum()

0

In [21]:
data['username'].isnull().sum()

0

In [22]:
data['initial_statement'].isnull().sum()

0

In [23]:
data.count()

username             1996
rating               1996
initial_statement    1996
username_country     1996
verified             1996
review               1979
usefulness            424
dtype: int64

In [24]:
data.head()

,username,rating,initial_statement,username_country,verified,review,usefulness
0,Asia underwood,4,It has good noise cancellation the only proble...,Reviewed in the United States ðŸ‡ºðŸ‡¸ on February 1...,1,"so when I bought these , I knew what i wanted ...",7 people found this helpful
1,Katie,4,Love these Headphones,Reviewed in the United States ðŸ‡ºðŸ‡¸ on February 2...,1,I bought these headphones last year and they h...,6 people found this helpful
2,Sean Connolly,4,Solid,Reviewed in the United States ðŸ‡ºðŸ‡¸ on December 1...,1,"The noise cancellation feature is very cool, a...",6 people found this helpful
3,Michelle,5,BUY IT RN,Reviewed in the United States ðŸ‡ºðŸ‡¸ on January 17...,1,i was a little bit skeptical at first because ...,7 people found this helpful
4,Jayden,5,Greta product slightly dirty,Reviewed in the United States ðŸ‡ºðŸ‡¸ on February 1...,1,Everything works! The only down sid Eid there ...,NaN

In [25]:
data = data.rename(columns={'username_country':'country'})

In [26]:
data.head()

,username,rating,initial_statement,country,verified,review,usefulness
0,Asia underwood,4,It has good noise cancellation the only proble...,Reviewed in the United States ðŸ‡ºðŸ‡¸ on February 1...,1,"so when I bought these , I knew what i wanted ...",7 people found this helpful
1,Katie,4,Love these Headphones,Reviewed in the United States ðŸ‡ºðŸ‡¸ on February 2...,1,I bought these headphones last year and they h...,6 people found this helpful
2,Sean Connolly,4,Solid,Reviewed in the United States ðŸ‡ºðŸ‡¸ on December 1...,1,"The noise cancellation feature is very cool, a...",6 people found this helpful
3,Michelle,5,BUY IT RN,Reviewed in the United States ðŸ‡ºðŸ‡¸ on January 17...,1,i was a little bit skeptical at first because ...,7 people found this helpful
4,Jayden,5,Greta product slightly dirty,Reviewed in the United States ðŸ‡ºðŸ‡¸ on February 1...,1,Everything works! The only down sid Eid there ...,NaN

In [27]:
data['date'] = data['country'].str.split(" ").str[-3:].str.join(" ")

In [28]:
data.head()

,username,rating,initial_statement,country,verified,review,usefulness,date
0,Asia underwood,4,It has good noise cancellation the only proble...,Reviewed in the United States ðŸ‡ºðŸ‡¸ on February 1...,1,"so when I bought these , I knew what i wanted ...",7 people found this helpful,"February 1, 2023"
1,Katie,4,Love these Headphones,Reviewed in the United States ðŸ‡ºðŸ‡¸ on February 2...,1,I bought these headphones last year and they h...,6 people found this helpful,"February 2, 2023"
2,Sean Connolly,4,Solid,Reviewed in the United States ðŸ‡ºðŸ‡¸ on December 1...,1,"The noise cancellation feature is very cool, a...",6 people found this helpful,"December 12, 2022"
3,Michelle,5,BUY IT RN,Reviewed in the United States ðŸ‡ºðŸ‡¸ on January 17...,1,i was a little bit skeptical at first because ...,7 people found this helpful,"January 17, 2023"
4,Jayden,5,Greta product slightly dirty,Reviewed in the United States ðŸ‡ºðŸ‡¸ on February 1...,1,Everything works! The only down sid Eid there ...,NaN,"February 15, 2023"

In [29]:
data["date"] = pd.to_datetime(data["date"])

In [30]:
data.head()

,username,rating,initial_statement,country,verified,review,usefulness,date
0,Asia underwood,4,It has good noise cancellation the only proble...,Reviewed in the United States ðŸ‡ºðŸ‡¸ on February 1...,1,"so when I bought these , I knew what i wanted ...",7 people found this helpful,2023-02-01
1,Katie,4,Love these Headphones,Reviewed in the United States ðŸ‡ºðŸ‡¸ on February 2...,1,I bought these headphones last year and they h...,6 people found this helpful,2023-02-02
2,Sean Connolly,4,Solid,Reviewed in the United States ðŸ‡ºðŸ‡¸ on December 1...,1,"The noise cancellation feature is very cool, a...",6 people found this helpful,2022-12-12
3,Michelle,5,BUY IT RN,Reviewed in the United States ðŸ‡ºðŸ‡¸ on January 17...,1,i was a little bit skeptical at first because ...,7 people found this helpful,2023-01-17
4,Jayden,5,Greta product slightly dirty,Reviewed in the United States ðŸ‡ºðŸ‡¸ on February 1...,1,Everything works! The only down sid Eid there ...,NaN,2023-02-15

In [31]:
data['country'] = data['country'].str.split(" ").str[3:5].str.join(" ")

In [32]:
data.head()

,username,rating,initial_statement,country,verified,review,usefulness,date
0,Asia underwood,4,It has good noise cancellation the only proble...,United States,1,"so when I bought these , I knew what i wanted ...",7 people found this helpful,2023-02-01
1,Katie,4,Love these Headphones,United States,1,I bought these headphones last year and they h...,6 people found this helpful,2023-02-02
2,Sean Connolly,4,Solid,United States,1,"The noise cancellation feature is very cool, a...",6 people found this helpful,2022-12-12
3,Michelle,5,BUY IT RN,United States,1,i was a little bit skeptical at first because ...,7 people found this helpful,2023-01-17
4,Jayden,5,Greta product slightly dirty,United States,1,Everything works! The only down sid Eid there ...,NaN,2023-02-15

In [33]:
data['usefulness'] = data['usefulness'].str.split(" ").str.get(0)

In [34]:
data.head()

,username,rating,initial_statement,country,verified,review,usefulness,date
0,Asia underwood,4,It has good noise cancellation the only proble...,United States,1,"so when I bought these , I knew what i wanted ...",7,2023-02-01
1,Katie,4,Love these Headphones,United States,1,I bought these headphones last year and they h...,6,2023-02-02
2,Sean Connolly,4,Solid,United States,1,"The noise cancellation feature is very cool, a...",6,2022-12-12
3,Michelle,5,BUY IT RN,United States,1,i was a little bit skeptical at first because ...,7,2023-01-17
4,Jayden,5,Greta product slightly dirty,United States,1,Everything works! The only down sid Eid there ...,NaN,2023-02-15

In [35]:
data['usefulness'].fillna(0)

0         7
1         6
2         6
3         7
4         0
       ...
1991      0
1992      0
1993    One
1994      0
1995    One
Name: usefulness, Length: 1996, dtype: object

In [36]:
data.count()

username             1996
rating               1996
initial_statement    1996
country              1996
verified             1996
review               1979
usefulness            424
date                 1996
dtype: int64

In [37]:
data.head()

,username,rating,initial_statement,country,verified,review,usefulness,date
0,Asia underwood,4,It has good noise cancellation the only proble...,United States,1,"so when I bought these , I knew what i wanted ...",7,2023-02-01
1,Katie,4,Love these Headphones,United States,1,I bought these headphones last year and they h...,6,2023-02-02
2,Sean Connolly,4,Solid,United States,1,"The noise cancellation feature is very cool, a...",6,2022-12-12
3,Michelle,5,BUY IT RN,United States,1,i was a little bit skeptical at first because ...,7,2023-01-17
4,Jayden,5,Greta product slightly dirty,United States,1,Everything works! The only down sid Eid there ...,NaN,2023-02-15

In [38]:
data['usefulness'] = data['usefulness'].replace({'One':1})

In [39]:
data.count()

username             1996
rating               1996
initial_statement    1996
country              1996
verified             1996
review               1979
usefulness            424
date                 1996
dtype: int64

In [40]:
data.head()

,username,rating,initial_statement,country,verified,review,usefulness,date
0,Asia underwood,4,It has good noise cancellation the only proble...,United States,1,"so when I bought these , I knew what i wanted ...",7,2023-02-01
1,Katie,4,Love these Headphones,United States,1,I bought these headphones last year and they h...,6,2023-02-02
2,Sean Connolly,4,Solid,United States,1,"The noise cancellation feature is very cool, a...",6,2022-12-12
3,Michelle,5,BUY IT RN,United States,1,i was a little bit skeptical at first because ...,7,2023-01-17
4,Jayden,5,Greta product slightly dirty,United States,1,Everything works! The only down sid Eid there ...,NaN,2023-02-15

In [41]:
data['usefulness'] = data['usefulness'].fillna(0)

In [42]:
data.head()

,username,rating,initial_statement,country,verified,review,usefulness,date
0,Asia underwood,4,It has good noise cancellation the only proble...,United States,1,"so when I bought these , I knew what i wanted ...",7,2023-02-01
1,Katie,4,Love these Headphones,United States,1,I bought these headphones last year and they h...,6,2023-02-02
2,Sean Connolly,4,Solid,United States,1,"The noise cancellation feature is very cool, a...",6,2022-12-12
3,Michelle,5,BUY IT RN,United States,1,i was a little bit skeptical at first because ...,7,2023-01-17
4,Jayden,5,Greta product slightly dirty,United States,1,Everything works! The only down sid Eid there ...,0,2023-02-15

In [43]:
data.count()

username             1996
rating               1996
initial_statement    1996
country              1996
verified             1996
review               1979
usefulness           1996
date                 1996
dtype: int64

In [44]:
data

,username,rating,initial_statement,country,verified,review,usefulness,date
0,Asia underwood,4,It has good noise cancellation the only proble...,United States,1,"so when I bought these , I knew what i wanted ...",7,2023-02-01
1,Katie,4,Love these Headphones,United States,1,I bought these headphones last year and they h...,6,2023-02-02
2,Sean Connolly,4,Solid,United States,1,"The noise cancellation feature is very cool, a...",6,2022-12-12
3,Michelle,5,BUY IT RN,United States,1,i was a little bit skeptical at first because ...,7,2023-01-17
4,Jayden,5,Greta product slightly dirty,United States,1,Everything works! The only down sid Eid there ...,0,2023-02-15
...,...,...,...,...,...,...,...,...
1991,PEDRO VALDOVINOS GAONA,2,Que el producto estÃ© en buenas condiciones.,ðŸ‡²ðŸ‡½ on,1,El producto se descargaba muy rÃ¡pido incluso l...,0,2021-06-24
1992,maac08,5,muy recomendables,ðŸ‡²ðŸ‡½ on,1,excelentes para usar en llamadas,0,2021-06-01
1993,Maximiliano,1,"La caja de los audÃ­fonos me llegÃ³ , de que est...",ðŸ‡²ðŸ‡½ on,1,Al parecer en algÃºn lugar se mojo la caja de l...,1,2022-09-19
1994,Antonio MerÃ©,5,Excelente,ðŸ‡²ðŸ‡½ on,1,Excelente,0,2021-05-22
1995,diego,1,Audifono derecho COMPLETAMENTE inservible.,ðŸ‡²ðŸ‡½ on,1,Todo el empaquetado estaba en muy buenas condi...,1,2021-10-04

In [45]:
data['country'].unique()

array(['United States', 'ðŸ‡²ðŸ‡½ on', 'ðŸ‡¨ðŸ‡¦ on'], dtype=object)

In [46]:
data.tail()

,username,rating,initial_statement,country,verified,review,usefulness,date
1991,PEDRO VALDOVINOS GAONA,2,Que el producto estÃ© en buenas condiciones.,ðŸ‡²ðŸ‡½ on,1,El producto se descargaba muy rÃ¡pido incluso l...,0,2021-06-24
1992,maac08,5,muy recomendables,ðŸ‡²ðŸ‡½ on,1,excelentes para usar en llamadas,0,2021-06-01
1993,Maximiliano,1,"La caja de los audÃ­fonos me llegÃ³ , de que est...",ðŸ‡²ðŸ‡½ on,1,Al parecer en algÃºn lugar se mojo la caja de l...,1,2022-09-19
1994,Antonio MerÃ©,5,Excelente,ðŸ‡²ðŸ‡½ on,1,Excelente,0,2021-05-22
1995,diego,1,Audifono derecho COMPLETAMENTE inservible.,ðŸ‡²ðŸ‡½ on,1,Todo el empaquetado estaba en muy buenas condi...,1,2021-10-04

In [47]:
data['country'] = data['country'].replace({'ðŸ‡²ðŸ‡½ on':'Mexico', 'ðŸ‡¨ðŸ‡¦ on':'Canada'})

In [48]:
data['country'].unique()

array(['United States', 'Mexico', 'Canada'], dtype=object)

In [49]:
data.to_csv('airpod_reviews_cleaned.csv', index=False)

In [50]:
data[data['country']=='Mexico'].count()

username             135
rating               135
initial_statement    135
country              135
verified             135
review               133
usefulness           135
date                 135
dtype: int64

In [51]:
data.count()

username             1996
rating               1996
initial_statement    1996
country              1996
verified             1996
review               1979
usefulness           1996
date                 1996
dtype: int64

In [52]:
data[data['country']=='Canada'].count()

username             14
rating               14
initial_statement    14
country              14
verified             14
review               14
usefulness           14
date                 14
dtype: int64

In [53]:
data[data['country']=='Canada']

,username,rating,initial_statement,country,verified,review,usefulness,date
1849,Anthony Idemili,4,AirPods Pro,Canada,1,Enjoying my newly bought AirPods Pro. Nice sou...,0,2023-02-09
1853,Abdullah,4,Excellent condition of item. Bad battery life ...,Canada,1,The quality of the airpods pro is excellent! N...,3,2022-11-30
1884,Denise Fidler,5,Buy New!!! These stopped working every 10 min ...,Canada,1,My grandson saved his birthday money to purcha...,3,2022-04-20
1897,ebensiter,5,Love them,Canada,1,Have 2 other makes that are pretty good but th...,3,2022-02-07
1898,Annick cÃ´tÃ©,5,Il a des Ã©gratignures,Canada,1,Il ne son pas en trÃ¨s bonne Ã©tat,0,2022-06-27
1899,Jashugan,1,One of the air pod was making static interfere...,Canada,1,One of the air pod was making static interfere...,0,2023-02-02
1900,Ivonise Morato de O. Capanema,5,Sound quality,Canada,1,I use this product to listen to music and podc...,1,2022-05-25
1921,HA,1,DO NOT PURCHASE ITEM,Canada,1,I bought these airpods and when I got them the...,11,2022-03-26
1967,Nelson Jean-Francois,1,Le produit que jâ€™ai reÃ§u ne fonctionne pas.,Canada,1,Ce produit Ã©tait dÃ©jÃ dÃ©fectueux. Je veux le r...,0,2022-05-29
1972,Manno,1,Air pods pro,Canada,1,You can get the air pods pro for the same pric...,8,2022-03-26
1973,Huynh Hua Hoang Hai,1,I disappointed with it,Canada,1,I disappointed with the sound quality and I co...,4,2022-01-15
1974,Barath,1,Damaged one & Amazon is irresponsible for the ...,Canada,1,The product is damaged & not good,0,2022-04-30
1975,Cindy 1010,1,Air pods,Canada,1,Didnâ€™t work.,1,2022-06-01
1980,Parminder Singh,1,Itâ€™s not working,Canada,1,Left airpod is not working since i open the box,5,2022-03-12

In [54]:
data.tail()

,username,rating,initial_statement,country,verified,review,usefulness,date
1991,PEDRO VALDOVINOS GAONA,2,Que el producto estÃ© en buenas condiciones.,Mexico,1,El producto se descargaba muy rÃ¡pido incluso l...,0,2021-06-24
1992,maac08,5,muy recomendables,Mexico,1,excelentes para usar en llamadas,0,2021-06-01
1993,Maximiliano,1,"La caja de los audÃ­fonos me llegÃ³ , de que est...",Mexico,1,Al parecer en algÃºn lugar se mojo la caja de l...,1,2022-09-19
1994,Antonio MerÃ©,5,Excelente,Mexico,1,Excelente,0,2021-05-22
1995,diego,1,Audifono derecho COMPLETAMENTE inservible.,Mexico,1,Todo el empaquetado estaba en muy buenas condi...,1,2021-10-04

In [55]:
data.count()

username             1996
rating               1996
initial_statement    1996
country              1996
verified             1996
review               1979
usefulness           1996
date                 1996
dtype: int64

In [56]:
data.shape[1]

8

In [57]:
data['positive'] = data['rating'].apply(lambda x: 1 if x > 3 else 0)

In [58]:
data

,username,rating,initial_statement,country,verified,review,usefulness,date,positive
0,Asia underwood,4,It has good noise cancellation the only proble...,United States,1,"so when I bought these , I knew what i wanted ...",7,2023-02-01,1
1,Katie,4,Love these Headphones,United States,1,I bought these headphones last year and they h...,6,2023-02-02,1
2,Sean Connolly,4,Solid,United States,1,"The noise cancellation feature is very cool, a...",6,2022-12-12,1
3,Michelle,5,BUY IT RN,United States,1,i was a little bit skeptical at first because ...,7,2023-01-17,1
4,Jayden,5,Greta product slightly dirty,United States,1,Everything works! The only down sid Eid there ...,0,2023-02-15,1
...,...,...,...,...,...,...,...,...,...
1991,PEDRO VALDOVINOS GAONA,2,Que el producto estÃ© en buenas condiciones.,Mexico,1,El producto se descargaba muy rÃ¡pido incluso l...,0,2021-06-24,0
1992,maac08,5,muy recomendables,Mexico,1,excelentes para usar en llamadas,0,2021-06-01,1
1993,Maximiliano,1,"La caja de los audÃ­fonos me llegÃ³ , de que est...",Mexico,1,Al parecer en algÃºn lugar se mojo la caja de l...,1,2022-09-19,0
1994,Antonio MerÃ©,5,Excelente,Mexico,1,Excelente,0,2021-05-22,1
1995,diego,1,Audifono derecho COMPLETAMENTE inservible.,Mexico,1,Todo el empaquetado estaba en muy buenas condi...,1,2021-10-04,0

In [59]:
data['review'].isnull().sum()

17

In [60]:
data = data.dropna(subset=['review'])

In [61]:
data['review'].isnull().sum()

0

In [62]:
data.shape[0]

1979

In [63]:
date_range = data['date'].min().strftime('%Y-%m-%d') + ' to ' + data['date'].max().strftime('%Y-%m-%d')

In [64]:
date_range

'2019-12-17 to 2023-02-21'

In [65]:
date_range_days = (data['date'].max() - data['date'].min()).days
date_range_days

1162

In [66]:
data

,username,rating,initial_statement,country,verified,review,usefulness,date,positive
0,Asia underwood,4,It has good noise cancellation the only proble...,United States,1,"so when I bought these , I knew what i wanted ...",7,2023-02-01,1
1,Katie,4,Love these Headphones,United States,1,I bought these headphones last year and they h...,6,2023-02-02,1
2,Sean Connolly,4,Solid,United States,1,"The noise cancellation feature is very cool, a...",6,2022-12-12,1
3,Michelle,5,BUY IT RN,United States,1,i was a little bit skeptical at first because ...,7,2023-01-17,1
4,Jayden,5,Greta product slightly dirty,United States,1,Everything works! The only down sid Eid there ...,0,2023-02-15,1
...,...,...,...,...,...,...,...,...,...
1991,PEDRO VALDOVINOS GAONA,2,Que el producto estÃ© en buenas condiciones.,Mexico,1,El producto se descargaba muy rÃ¡pido incluso l...,0,2021-06-24,0
1992,maac08,5,muy recomendables,Mexico,1,excelentes para usar en llamadas,0,2021-06-01,1
1993,Maximiliano,1,"La caja de los audÃ­fonos me llegÃ³ , de que est...",Mexico,1,Al parecer en algÃºn lugar se mojo la caja de l...,1,2022-09-19,0
1994,Antonio MerÃ©,5,Excelente,Mexico,1,Excelente,0,2021-05-22,1
1995,diego,1,Audifono derecho COMPLETAMENTE inservible.,Mexico,1,Todo el empaquetado estaba en muy buenas condi...,1,2021-10-04,0

In [67]:
data['positive'].unique()

array([1, 0], dtype=int64)

In [69]:
data['verified'].unique()

array([1, 'Early Reviewer Rewards', 0], dtype=object)

In [70]:
early_reviewer_rewards = data[data['verified'] == 'Early Reviewer Rewards']
early_reviewer_rewards

,username,rating,initial_statement,country,verified,review,usefulness,date,positive
787,John R.,4,Disappointed,United States,Early Reviewer Rewards,Cost a lot more where I got them no one had th...,1,2020-01-04,1
1218,Subzer089,5,Better than Beats Pro!,United States,Early Reviewer Rewards,"These surpassed my beats pro. Get them guys, w...",0,2020-01-06,1
1322,Bobbie S,5,No issues,United States,Early Reviewer Rewards,Working good so far!,0,2020-01-09,1
1360,Claudio,5,ðŸ‘»,United States,Early Reviewer Rewards,ðŸ‘»ðŸ‘»ðŸ‘»ðŸ‘»,1,2020-01-08,1
1371,Amazon Customer,5,Airpod pro,United States,Early Reviewer Rewards,Great!,0,2020-01-11,1

In [71]:
data['verified'] = data['verified'].replace('Early Reviewer Rewards', 1)

C:\Users\kevin\AppData\Local\Temp\ipykernel_2472\3005961612.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['verified'] = data['verified'].replace('Early Reviewer Rewards', 1)

In [73]:
data['usefulness'].unique()

array(['7', '6', 0, '3', '4', '5', 1, '14', '9', '24', '2', '16', '17',
       '20', '11', '21', '13', '8', '31', '232', '18', '274', '10', '150',
       '140', '168', '30', '12', '23', '55', '35', '370', '363', '505',
       '40', '26'], dtype=object)

In [74]:
data['date'].unique()

array(['2023-02-01T00:00:00.000000000', '2023-02-02T00:00:00.000000000',
       '2022-12-12T00:00:00.000000000', '2023-01-17T00:00:00.000000000',
       '2023-02-15T00:00:00.000000000', '2023-01-26T00:00:00.000000000',
       '2022-12-24T00:00:00.000000000', '2023-02-16T00:00:00.000000000',
       '2023-01-04T00:00:00.000000000', '2023-02-13T00:00:00.000000000',
       '2023-01-11T00:00:00.000000000', '2023-02-21T00:00:00.000000000',
       '2022-12-04T00:00:00.000000000', '2023-01-21T00:00:00.000000000',
       '2023-02-08T00:00:00.000000000', '2022-12-30T00:00:00.000000000',
       '2022-09-23T00:00:00.000000000', '2022-11-21T00:00:00.000000000',
       '2023-02-03T00:00:00.000000000', '2023-01-12T00:00:00.000000000',
       '2022-11-06T00:00:00.000000000', '2023-01-22T00:00:00.000000000',
       '2023-01-18T00:00:00.000000000', '2022-11-07T00:00:00.000000000',
       '2023-02-07T00:00:00.000000000', '2022-10-15T00:00:00.000000000',
       '2022-07-30T00:00:00.000000000', '2022-11-13T00:00:00.000000000',
       '2022-10-24T00:00:00.000000000', '2023-01-16T00:00:00.000000000',
       '2022-12-14T00:00:00.000000000', '2023-01-06T00:00:00.000000000',
       '2023-01-08T00:00:00.000000000', '2022-09-20T00:00:00.000000000',
       '2022-12-06T00:00:00.000000000', '2022-08-05T00:00:00.000000000',
       '2022-03-31T00:00:00.000000000', '2022-10-31T00:00:00.000000000',
       '2021-05-29T00:00:00.000000000', '2022-10-13T00:00:00.000000000',
       '2022-12-25T00:00:00.000000000', '2022-12-26T00:00:00.000000000',
       '2023-01-14T00:00:00.000000000', '2023-01-01T00:00:00.000000000',
       '2023-01-27T00:00:00.000000000', '2022-10-27T00:00:00.000000000',
       '2023-01-09T00:00:00.000000000', '2022-09-04T00:00:00.000000000',
       '2023-01-02T00:00:00.000000000', '2022-09-01T00:00:00.000000000',
       '2022-11-23T00:00:00.000000000', '2021-05-13T00:00:00.000000000',
       '2022-12-18T00:00:00.000000000', '2022-09-05T00:00:00.000000000',
       '2022-07-31T00:00:00.000000000', '2022-12-05T00:00:00.000000000',
       '2022-09-15T00:00:00.000000000', '2022-09-08T00:00:00.000000000',
       '2022-05-13T00:00:00.000000000', '2022-10-23T00:00:00.000000000',
       '2022-08-09T00:00:00.000000000', '2022-07-12T00:00:00.000000000',
       '2022-11-16T00:00:00.000000000', '2022-05-10T00:00:00.000000000',
       '2022-07-22T00:00:00.000000000', '2022-11-28T00:00:00.000000000',
       '2022-07-07T00:00:00.000000000', '2022-10-17T00:00:00.000000000',
       '2022-10-09T00:00:00.000000000', '2022-12-10T00:00:00.000000000',
       '2021-10-02T00:00:00.000000000', '2022-10-03T00:00:00.000000000',
       '2022-10-01T00:00:00.000000000', '2022-08-08T00:00:00.000000000',
       '2022-11-15T00:00:00.000000000', '2022-09-18T00:00:00.000000000',
       '2022-06-29T00:00:00.000000000', '2022-06-25T00:00:00.000000000',
       '2022-11-05T00:00:00.000000000', '2022-11-08T00:00:00.000000000',
       '2022-08-26T00:00:00.000000000', '2021-09-15T00:00:00.000000000',
       '2021-09-26T00:00:00.000000000', '2022-07-15T00:00:00.000000000',
       '2022-05-16T00:00:00.000000000', '2021-10-15T00:00:00.000000000',
       '2021-04-15T00:00:00.000000000', '2022-03-12T00:00:00.000000000',
       '2022-08-24T00:00:00.000000000', '2022-08-31T00:00:00.000000000',
       '2022-04-11T00:00:00.000000000', '2022-09-26T00:00:00.000000000',
       '2022-10-16T00:00:00.000000000', '2022-09-30T00:00:00.000000000',
       '2022-11-09T00:00:00.000000000', '2022-09-13T00:00:00.000000000',
       '2022-10-11T00:00:00.000000000', '2022-06-03T00:00:00.000000000',
       '2022-09-06T00:00:00.000000000', '2022-09-19T00:00:00.000000000',
       '2022-10-05T00:00:00.000000000', '2022-08-06T00:00:00.000000000',
       '2022-11-18T00:00:00.000000000', '2021-11-13T00:00:00.000000000',
       '2022-04-14T00:00:00.000000000', '2021-03-03T00:00:00.000000000',
       '2022-11-04T00:00:00.000000000', '2021-05-20T00:00:00.000000000',
       '2022-09-22T00:00:00.000000000', '2022-10-21T00:00:00.000000000',
       '2022-07-03T00:00:00.000000000', '2022-03-01T00:00:00.000000000',
       '2022-07-28T00:00:00.000000000', '2021-03-29T00:00:00.000000000',
       '2021-12-12T00:00:00.000000000', '2021-06-03T00:00:00.000000000',
       '2022-10-02T00:00:00.000000000', '2022-12-21T00:00:00.000000000',
       '2021-12-15T00:00:00.000000000', '2021-07-14T00:00:00.000000000',
       '2022-09-21T00:00:00.000000000', '2022-05-18T00:00:00.000000000',
       '2022-02-28T00:00:00.000000000', '2022-03-23T00:00:00.000000000',
       '2021-08-06T00:00:00.000000000', '2022-05-02T00:00:00.000000000',
       '2022-10-18T00:00:00.000000000', '2022-09-29T00:00:00.000000000',
       '2022-03-26T00:00:00.000000000', '2022-12-28T00:00:00.000000000',
       '2022-09-10T00:00:00.000000000', '2023-02-09T00:00:00.000000000',
       '2022-01-13T00:00:00.000000000', '2022-05-17T00:00:00.000000000',
       '2021-09-25T00:00:00.000000000', '2022-03-18T00:00:00.000000000',
       '2022-10-25T00:00:00.000000000', '2022-06-08T00:00:00.000000000',
       '2022-08-28T00:00:00.000000000', '2022-09-24T00:00:00.000000000',
       '2022-10-10T00:00:00.000000000', '2021-09-05T00:00:00.000000000',
       '2022-08-02T00:00:00.000000000', '2022-03-22T00:00:00.000000000',
       '2022-03-10T00:00:00.000000000', '2022-08-19T00:00:00.000000000',
       '2021-10-19T00:00:00.000000000', '2022-10-08T00:00:00.000000000',
       '2022-08-20T00:00:00.000000000', '2022-12-11T00:00:00.000000000',
       '2022-08-21T00:00:00.000000000', '2022-06-01T00:00:00.000000000',
       '2022-09-02T00:00:00.000000000', '2021-12-26T00:00:00.000000000',
       '2022-06-16T00:00:00.000000000', '2021-02-09T00:00:00.000000000',
       '2022-07-13T00:00:00.000000000', '2021-07-29T00:00:00.000000000',
       '2022-05-11T00:00:00.000000000', '2022-01-04T00:00:00.000000000',
       '2023-02-06T00:00:00.000000000', '2021-10-28T00:00:00.000000000',
       '2022-10-19T00:00:00.000000000', '2022-02-21T00:00:00.000000000',
       '2021-09-02T00:00:00.000000000', '2022-10-28T00:00:00.000000000',
       '2022-08-04T00:00:00.000000000', '2022-08-15T00:00:00.000000000',
       '2022-04-25T00:00:00.000000000', '2021-07-16T00:00:00.000000000',
       '2021-08-21T00:00:00.000000000', '2022-09-16T00:00:00.000000000',
       '2022-02-11T00:00:00.000000000', '2022-07-23T00:00:00.000000000',
       '2022-07-10T00:00:00.000000000', '2022-05-23T00:00:00.000000000',
       '2022-01-31T00:00:00.000000000', '2022-09-03T00:00:00.000000000',
       '2021-05-25T00:00:00.000000000', '2022-02-04T00:00:00.000000000',
       '2021-12-03T00:00:00.000000000', '2023-02-05T00:00:00.000000000',
       '2021-12-11T00:00:00.000000000', '2022-08-12T00:00:00.000000000',
       '2022-07-20T00:00:00.000000000', '2021-06-12T00:00:00.000000000',
       '2020-05-07T00:00:00.000000000', '2021-05-31T00:00:00.000000000',
       '2022-06-10T00:00:00.000000000', '2021-10-25T00:00:00.000000000',
       '2022-05-25T00:00:00.000000000', '2021-06-15T00:00:00.000000000',
       '2022-07-17T00:00:00.000000000', '2021-07-23T00:00:00.000000000',
       '2022-08-07T00:00:00.000000000', '2021-05-21T00:00:00.000000000',
       '2022-08-16T00:00:00.000000000', '2021-12-18T00:00:00.000000000',
       '2022-03-29T00:00:00.000000000', '2020-11-05T00:00:00.000000000',
       '2022-06-23T00:00:00.000000000', '2022-01-01T00:00:00.000000000',
       '2021-07-09T00:00:00.000000000', '2022-07-14T00:00:00.000000000',
       '2021-11-25T00:00:00.000000000', '2022-08-23T00:00:00.000000000',
       '2022-07-24T00:00:00.000000000', '2021-04-26T00:00:00.000000000',
       '2022-08-18T00:00:00.000000000', '2022-08-11T00:00:00.000000000',
       '2021-09-29T00:00:00.000000000', '2021-03-16T00:00:00.000000000',
       '2021-10-29T00:00:00.000000000', '2022-03-11T00:00:00.000000000',
       '2022-01-30T00:00:00.000000000', '2022-06-06T00:00:00.000000000',
       '2022-01-03T00:00:00.000000000', '2020-09-23T00:00:00.000000000',
       '2021-12-06T00:00:00.000000000', '2021-03-15T00:00:00.000000000',
       '2022-05-22T00:00:00.000000000', '2021-04-18T00:00:00.000000000',
       '2021-08-04T00:00:00.000000000', '2022-01-20T00:00:00.000000000',
       '2021-12-25T00:00:00.000000000', '2020-07-09T00:00:00.000000000',
       '2021-07-11T00:00:00.000000000', '2022-06-07T00:00:00.000000000',
       '2021-04-17T00:00:00.000000000', '2021-06-07T00:00:00.000000000',
       '2022-04-28T00:00:00.000000000', '2022-08-01T00:00:00.000000000',
       '2020-04-14T00:00:00.000000000', '2022-07-19T00:00:00.000000000',
       '2022-05-24T00:00:00.000000000', '2021-03-05T00:00:00.000000000',
       '2022-03-28T00:00:00.000000000', '2020-12-16T00:00:00.000000000',
       '2021-02-17T00:00:00.000000000', '2022-04-09T00:00:00.000000000',
       '2021-06-04T00:00:00.000000000', '2022-08-03T00:00:00.000000000',
       '2021-07-01T00:00:00.000000000', '2022-05-20T00:00:00.000000000',
       '2022-05-30T00:00:00.000000000', '2021-08-01T00:00:00.000000000',
       '2021-06-19T00:00:00.000000000', '2022-03-21T00:00:00.000000000',
       '2022-03-08T00:00:00.000000000', '2021-08-24T00:00:00.000000000',
       '2022-04-08T00:00:00.000000000', '2022-03-06T00:00:00.000000000',
       '2021-05-19T00:00:00.000000000', '2021-06-28T00:00:00.000000000',
       '2020-12-13T00:00:00.000000000', '2022-06-18T00:00:00.000000000',
       '2021-11-12T00:00:00.000000000', '2021-04-14T00:00:00.000000000',
       '2020-12-18T00:00:00.000000000', '2022-11-30T00:00:00.000000000',
       '2023-02-11T00:00:00.000000000', '2021-06-09T00:00:00.000000000',
       '2021-06-14T00:00:00.000000000', '2023-01-30T00:00:00.000000000',
       '2022-09-07T00:00:00.000000000', '2022-04-26T00:00:00.000000000',
       '2022-06-09T00:00:00.000000000', '2021-06-30T00:00:00.000000000',
       '2021-07-20T00:00:00.000000000', '2021-11-26T00:00:00.000000000',
       '2022-06-28T00:00:00.000000000', '2021-01-10T00:00:00.000000000',
       '2021-10-16T00:00:00.000000000', '2022-04-17T00:00:00.000000000',
       '2021-11-04T00:00:00.000000000', '2022-06-24T00:00:00.000000000',
       '2021-03-24T00:00:00.000000000', '2020-12-05T00:00:00.000000000',
       '2022-01-05T00:00:00.000000000', '2022-04-07T00:00:00.000000000',
       '2022-04-29T00:00:00.000000000', '2021-09-10T00:00:00.000000000',
       '2021-08-29T00:00:00.000000000', '2022-02-10T00:00:00.000000000',
       '2022-05-09T00:00:00.000000000', '2021-04-11T00:00:00.000000000',
       '2021-07-24T00:00:00.000000000', '2021-08-14T00:00:00.000000000',
       '2020-12-01T00:00:00.000000000', '2022-03-13T00:00:00.000000000',
       '2020-08-18T00:00:00.000000000', '2023-01-15T00:00:00.000000000',
       '2022-02-17T00:00:00.000000000', '2021-05-05T00:00:00.000000000',
       '2020-08-22T00:00:00.000000000', '2022-12-02T00:00:00.000000000',
       '2022-04-18T00:00:00.000000000', '2020-08-31T00:00:00.000000000',
       '2021-04-06T00:00:00.000000000', '2023-01-25T00:00:00.000000000',
       '2021-10-27T00:00:00.000000000', '2021-05-07T00:00:00.000000000',
       '2022-05-05T00:00:00.000000000', '2022-02-25T00:00:00.000000000',
       '2021-07-02T00:00:00.000000000', '2022-09-28T00:00:00.000000000',
       '2022-04-12T00:00:00.000000000', '2021-02-19T00:00:00.000000000',
       '2022-05-01T00:00:00.000000000', '2021-09-08T00:00:00.000000000',
       '2021-07-19T00:00:00.000000000', '2021-12-24T00:00:00.000000000',
       '2022-02-18T00:00:00.000000000', '2020-06-24T00:00:00.000000000',
       '2020-06-06T00:00:00.000000000', '2021-05-09T00:00:00.000000000',
       '2022-01-11T00:00:00.000000000', '2020-11-21T00:00:00.000000000',
       '2021-06-17T00:00:00.000000000', '2020-12-26T00:00:00.000000000',
       '2021-12-23T00:00:00.000000000', '2022-01-16T00:00:00.000000000',
       '2022-01-15T00:00:00.000000000', '2021-09-24T00:00:00.000000000',
       '2022-04-19T00:00:00.000000000', '2022-03-27T00:00:00.000000000',
       '2022-08-25T00:00:00.000000000', '2021-06-23T00:00:00.000000000',
       '2021-07-04T00:00:00.000000000', '2020-12-20T00:00:00.000000000',
       '2022-04-15T00:00:00.000000000', '2022-03-04T00:00:00.000000000',
       '2021-12-22T00:00:00.000000000', '2021-07-26T00:00:00.000000000',
       '2021-08-20T00:00:00.000000000', '2021-02-04T00:00:00.000000000',
       '2020-11-11T00:00:00.000000000', '2023-01-19T00:00:00.000000000',
       '2020-11-10T00:00:00.000000000', '2023-01-29T00:00:00.000000000',
       '2021-05-22T00:00:00.000000000', '2021-04-07T00:00:00.000000000',
       '2020-11-28T00:00:00.000000000', '2020-08-09T00:00:00.000000000',
       '2021-01-15T00:00:00.000000000', '2021-07-31T00:00:00.000000000',
       '2021-08-17T00:00:00.000000000', '2021-05-15T00:00:00.000000000',
       '2021-09-27T00:00:00.000000000', '2022-04-24T00:00:00.000000000',
       '2020-06-12T00:00:00.000000000', '2020-11-24T00:00:00.000000000',
       '2022-04-05T00:00:00.000000000', '2021-05-10T00:00:00.000000000',
       '2021-03-30T00:00:00.000000000', '2021-07-30T00:00:00.000000000',
       '2021-09-20T00:00:00.000000000', '2022-12-27T00:00:00.000000000',
       '2021-12-31T00:00:00.000000000', '2021-06-18T00:00:00.000000000',
       '2022-05-06T00:00:00.000000000', '2022-02-26T00:00:00.000000000',
       '2021-05-04T00:00:00.000000000', '2021-04-01T00:00:00.000000000',
       '2021-08-07T00:00:00.000000000', '2021-06-10T00:00:00.000000000',
       '2021-11-17T00:00:00.000000000', '2020-01-05T00:00:00.000000000',
       '2021-03-07T00:00:00.000000000', '2021-09-11T00:00:00.000000000',
       '2022-01-06T00:00:00.000000000', '2021-04-04T00:00:00.000000000',
       '2020-09-01T00:00:00.000000000', '2021-03-10T00:00:00.000000000',
       '2021-10-13T00:00:00.000000000', '2022-02-23T00:00:00.000000000',
       '2022-03-09T00:00:00.000000000', '2022-07-02T00:00:00.000000000',
       '2020-10-11T00:00:00.000000000', '2022-01-28T00:00:00.000000000',
       '2021-10-06T00:00:00.000000000', '2021-11-28T00:00:00.000000000',
       '2020-02-11T00:00:00.000000000', '2021-05-12T00:00:00.000000000',
       '2021-07-18T00:00:00.000000000', '2022-02-15T00:00:00.000000000',
       '2022-07-25T00:00:00.000000000', '2022-03-02T00:00:00.000000000',
       '2021-05-27T00:00:00.000000000', '2022-01-08T00:00:00.000000000',
       '2020-08-17T00:00:00.000000000', '2020-01-18T00:00:00.000000000',
       '2022-01-07T00:00:00.000000000', '2022-08-27T00:00:00.000000000',
       '2022-06-30T00:00:00.000000000', '2023-01-31T00:00:00.000000000',
       '2021-12-08T00:00:00.000000000', '2020-07-17T00:00:00.000000000',
       '2021-06-05T00:00:00.000000000', '2022-03-07T00:00:00.000000000',
       '2022-03-25T00:00:00.000000000', '2020-06-11T00:00:00.000000000',
       '2021-11-11T00:00:00.000000000', '2021-07-06T00:00:00.000000000',
       '2021-12-30T00:00:00.000000000', '2021-04-13T00:00:00.000000000',
       '2021-03-13T00:00:00.000000000', '2021-05-30T00:00:00.000000000',
       '2022-10-26T00:00:00.000000000', '2021-03-06T00:00:00.000000000',
       '2021-09-12T00:00:00.000000000', '2020-05-12T00:00:00.000000000',
       '2020-07-14T00:00:00.000000000', '2022-11-29T00:00:00.000000000',
       '2021-09-21T00:00:00.000000000', '2022-02-08T00:00:00.000000000',
       '2021-12-17T00:00:00.000000000', '2021-11-05T00:00:00.000000000',
       '2021-10-20T00:00:00.000000000', '2022-01-02T00:00:00.000000000',
       '2021-01-06T00:00:00.000000000', '2021-08-16T00:00:00.000000000',
       '2021-03-04T00:00:00.000000000', '2021-07-07T00:00:00.000000000',
       '2021-12-09T00:00:00.000000000', '2021-02-27T00:00:00.000000000',
       '2021-07-10T00:00:00.000000000', '2021-11-06T00:00:00.000000000',
       '2021-06-01T00:00:00.000000000', '2021-05-28T00:00:00.000000000',
       '2021-11-24T00:00:00.000000000', '2022-11-10T00:00:00.000000000',
       '2022-10-30T00:00:00.000000000', '2021-07-13T00:00:00.000000000',
       '2021-03-23T00:00:00.000000000', '2022-12-16T00:00:00.000000000',
       '2022-06-12T00:00:00.000000000', '2021-08-25T00:00:00.000000000',
       '2021-04-16T00:00:00.000000000', '2020-08-27T00:00:00.000000000',
       '2020-07-30T00:00:00.000000000', '2020-09-18T00:00:00.000000000',
       '2021-02-05T00:00:00.000000000', '2021-04-22T00:00:00.000000000',
       '2022-08-13T00:00:00.000000000', '2022-12-09T00:00:00.000000000',
       '2022-06-21T00:00:00.000000000', '2021-04-28T00:00:00.000000000',
       '2021-09-14T00:00:00.000000000', '2022-01-10T00:00:00.000000000',
       '2021-11-14T00:00:00.000000000', '2021-04-03T00:00:00.000000000',
       '2021-10-12T00:00:00.000000000', '2021-05-11T00:00:00.000000000',
       '2021-03-31T00:00:00.000000000', '2021-05-26T00:00:00.000000000',
       '2021-05-03T00:00:00.000000000', '2020-12-23T00:00:00.000000000',
       '2021-06-21T00:00:00.000000000', '2021-06-27T00:00:00.000000000',
       '2020-11-12T00:00:00.000000000', '2021-04-27T00:00:00.000000000',
       '2021-08-03T00:00:00.000000000', '2020-03-21T00:00:00.000000000',
       '2020-11-17T00:00:00.000000000', '2021-03-27T00:00:00.000000000',
       '2021-10-17T00:00:00.000000000', '2021-07-05T00:00:00.000000000',
       '2021-10-26T00:00:00.000000000', '2021-05-16T00:00:00.000000000',
       '2023-01-13T00:00:00.000000000', '2021-03-28T00:00:00.000000000',
       '2021-11-23T00:00:00.000000000', '2021-04-20T00:00:00.000000000',
       '2021-03-18T00:00:00.000000000', '2021-04-30T00:00:00.000000000',
       '2023-01-03T00:00:00.000000000', '2021-06-29T00:00:00.000000000',
       '2021-09-03T00:00:00.000000000', '2021-04-05T00:00:00.000000000',
       '2020-07-12T00:00:00.000000000', '2021-04-02T00:00:00.000000000',
       '2021-05-14T00:00:00.000000000', '2021-08-27T00:00:00.000000000',
       '2022-12-15T00:00:00.000000000', '2021-02-13T00:00:00.000000000',
       '2022-12-01T00:00:00.000000000', '2021-04-08T00:00:00.000000000',
       '2021-04-09T00:00:00.000000000', '2021-08-31T00:00:00.000000000',
       '2020-04-20T00:00:00.000000000', '2022-01-25T00:00:00.000000000',
       '2020-11-04T00:00:00.000000000', '2022-11-25T00:00:00.000000000',
       '2020-09-24T00:00:00.000000000', '2021-10-10T00:00:00.000000000',
       '2021-08-11T00:00:00.000000000', '2021-04-25T00:00:00.000000000',
       '2021-07-03T00:00:00.000000000', '2021-08-15T00:00:00.000000000',
       '2020-11-07T00:00:00.000000000', '2021-09-09T00:00:00.000000000',
       '2021-11-16T00:00:00.000000000', '2021-05-24T00:00:00.000000000',
       '2021-04-29T00:00:00.000000000', '2021-02-16T00:00:00.000000000',
       '2021-09-23T00:00:00.000000000', '2022-09-25T00:00:00.000000000',
       '2020-01-04T00:00:00.000000000', '2022-07-06T00:00:00.000000000',
       '2021-08-13T00:00:00.000000000', '2023-01-24T00:00:00.000000000',
       '2020-12-10T00:00:00.000000000', '2021-06-13T00:00:00.000000000',
       '2021-11-15T00:00:00.000000000', '2021-10-21T00:00:00.000000000',
       '2021-09-06T00:00:00.000000000', '2021-08-26T00:00:00.000000000',
       '2020-02-09T00:00:00.000000000', '2020-08-03T00:00:00.000000000',
       '2021-11-18T00:00:00.000000000', '2021-07-08T00:00:00.000000000',
       '2021-05-17T00:00:00.000000000', '2020-03-12T00:00:00.000000000',
       '2020-08-01T00:00:00.000000000', '2020-10-15T00:00:00.000000000',
       '2021-08-05T00:00:00.000000000', '2021-07-25T00:00:00.000000000',
       '2021-11-10T00:00:00.000000000', '2020-06-26T00:00:00.000000000',
       '2021-03-01T00:00:00.000000000', '2020-07-19T00:00:00.000000000',
       '2021-03-22T00:00:00.000000000', '2020-03-14T00:00:00.000000000',
       '2020-04-24T00:00:00.000000000', '2020-11-25T00:00:00.000000000',
       '2022-07-29T00:00:00.000000000', '2021-06-08T00:00:00.000000000',
       '2021-07-21T00:00:00.000000000', '2020-03-05T00:00:00.000000000',
       '2020-08-20T00:00:00.000000000', '2022-11-14T00:00:00.000000000',
       '2021-03-20T00:00:00.000000000', '2020-10-14T00:00:00.000000000',
       '2021-03-08T00:00:00.000000000', '2022-02-07T00:00:00.000000000',

In [75]:
data['positive'].unique()

array([1, 0], dtype=int64)

In [76]:
data.count()

username             1979
rating               1979
initial_statement    1979
country              1979
verified             1979
review               1979
usefulness           1979
date                 1979
positive             1979
dtype: int64

In [77]:
data.to_csv('airpod_reviews_cleaned.csv', index=False)